### ISSUE TITLE
Missing loader file

### ISSUE THREAD

**Issue by ashmaroli** [kramdown/converter-pdf#1]
Since this gem is not loaded automatically by kramdown. the recommended way of usage *may fail* for some users.
```ruby
require 'kramdown'
require 'kramdown/converter/pdf'

Kramdown::Document.new(text).to_pdf
```
A `lib/kramdown-converter-pdf.rb` may need to exist which in-turn loads `kramdown/converter/pdf.rb`.

(Additionally, this route would mean consistent behavior across other kramdown-extensions)

**Comment by gettalong** [comment]
Thanks for reporting this!

The code you included will always work since those are just the standard paths. However, you are right that the convenience loader file is missing. I have fixed this and released a new version of the gem.
